2025/01/20 14:19:56 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.3, server: site2.local, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.5:9000", host: "site2.local"
2025/01/20 14:19:59 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.3, server: site2.local, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.5:9000", host: "site2.local"
2025/01/20 14:22:04 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.2, server: site2.local, request: "GET / HTTP/1.1", upstream: "fastcgi://172.23.0.4:9000", host: "site2.local"
2025/01/20 14:22:06 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.2, server: site2.local, request: "GET / HTTP/1.1", upstream: "fastcgi://172.23.0.4:9000", host: "site2.local"
2025/01/20 14:25:29 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.3, server: site2.local, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.5:9000", host: "site2.local"
2025/01/20 14:25:31 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.3, server: site2.local, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.5:9000", host: "site2.local"
